apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accessing-files.fullname" . }}
type: Opaque
data:
{{/*returns base64 string of secrets. NOT RECOMMENDED because secrets will be packaged into chart. For demo only*/}}
{{ (.Files.Glob "files/*.properties").AsSecrets | indent 2 }}